_perf:
    resource: "@MoschiniPerfToolBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /perf

_sites:
    resource: "@MoschiniPerfToolBundle/Controller/SitesController.php"
    type:     annotation
    prefix:   /sites

